import type { ComponentScenario, AgentScenario, AdaptScenario } from '@/types'

export const SC_CONFIRMATION: ComponentScenario = {
  type: 'component',
  title: 'ConfirmationTransfer',
  tokens: [
    { name: 'color.status.trust', value: '#1a6bff', swatch: '#1a6bff' },
    { name: 'color.amount.high', value: '#f5f0e8', swatch: '#f5f0e8' },
    { name: 'typography.weight', value: '500', swatch: null },
    { name: 'spacing.breath', value: '32px', swatch: null },
  ],
  components: ['AmountDisplay', 'BiometricPrompt', 'ConfirmationCard'],
  rules: ['Montant > 5k → biométrie requise', 'Ton : sobre, confiant', 'Animation : lente, délibérée'],
  refine: ['Rendre plus rassurant', 'Version light mode', "Ajouter état d'erreur", 'Réduire la friction'],
  mcp: JSON.stringify(
    {
      server: 'contextlayer',
      component: 'ConfirmationTransfer',
      tokens: {
        'color.status.trust': '#1a6bff',
        'color.amount.high': '#f5f0e8',
        'typography.weight': '500',
        'spacing.breath': '32px',
      },
      rules: { 'threshold.biometric': 5000, 'animation.timing': 'slow' },
      latency: '340ms',
    },
    null,
    2
  ),
  story: `// ConfirmationTransfer story
// Generated by ContextLayer

export const HighAmount = {
  args: {
    amount: 8450,
    recipient: "Marie Dupont",
    requiresBiometric: true,
    theme: "dark",
  },
}`,
}

export const SC_ADVISOR: AgentScenario = {
  type: 'agent',
  title: 'VoltaAdvisor',
  nodes: [
    { label: "Détection d'intention", status: 'active', detail: "Classifie parmi : information, action, anxiété, urgence." },
    { label: 'Profil émotionnel', status: 'active', detail: "Score anxiété 0–1. Si > 0.6 → ralentir, augmenter l'empathie." },
    { label: 'Tempo de réponse', status: 'warning', sub: 'Laisser respirer', detail: 'Pause 800ms. Poser une question avant de suggérer.' },
    { label: 'Incertitude > 0.7 → ne pas recommander', status: 'rule', detail: 'Si confiance < 0.3, rediriger vers conseiller humain.' },
    { label: 'Escalade humain', status: 'passive', detail: "Déclenché si 3 refus ou score anxiété > 0.85." },
  ],
  persona: [['Rassurant', 'Ton'], ['Lent', 'Rythme'], ['Humble', 'Certitude'], ['Élevée', 'Empathie']],
  sliders: [
    { name: 'Empathie', key: 'empathy', value: 80 },
    { name: 'Tempo (lenteur)', key: 'tempo', value: 70 },
    { name: 'Certitude autorisée', key: 'certainty', value: 30 },
    { name: 'Seuil escalade', key: 'escalation', value: 85 },
  ],
  refine: ['Mode expert', 'Ajouter nœud fiscal', 'Version multilingue', 'Réduire escalades'],
  mcp: JSON.stringify(
    {
      server: 'agentspec',
      agent: 'VoltaAdvisor',
      persona: { tone: 'reassuring', speed: 'slow', certainty: 'humble', empathy: 'high' },
      guardrails: { uncertainty_threshold: 0.7, anxiety_escalation: 0.85, max_refusals: 3 },
    },
    null,
    2
  ),
  story: `// VoltaAdvisor — AgentSpec export

system_prompt:
  Tu es Volta Advisor.
  Règles :
  - Poser une question avant de suggérer
  - Si incertitude > 0.7 : rediriger
  - Tempo : 800ms de pause

guardrails:
  uncertainty_threshold: 0.7
  anxiety_escalation: 0.85`,
}

export const SC_WEARABLE: AdaptScenario = {
  type: 'adapt',
  title: 'AmountDisplay → Watch',
  mutations: [
    { from: 'font-size: 48px', to: 'font-size: 22px', why: 'Écran 44mm' },
    { from: '3 lignes', to: '2 lignes max', why: 'Lisibilité' },
    { from: 'animation: fadeIn 300ms', to: 'haptic: medium + 80ms', why: 'Retour physique' },
    { from: 'padding: 32px', to: 'padding: 8px', why: 'Surface réduite' },
  ],
  inherited: ['color.status.trust', 'color.amount.high', 'typography.family', 'border.radius.card'],
  refine: ['Optimiser Series 9', 'Ajouter complication', 'Haptic plus fort', 'Accessibilité AAA'],
  mcp: JSON.stringify(
    {
      server: 'contextlayer',
      operation: 'adapt',
      source: 'AmountDisplay@mobile',
      target: 'AmountDisplay@watchOS',
      mutations: {
        'typography.size.amount': '22px',
        'layout.lines.max': 2,
        'feedback.type': 'haptic+visual',
        'spacing.padding': '8px',
      },
      diff: '3 modified / 14 inherited',
    },
    null,
    2
  ),
  story: `// AmountDisplay — Watch variant

export const WatchOS = {
  args: {
    amount: 8450,
    platform: "watchOS",
    maxLines: 2,
    hapticFeedback: "medium",
    fontSize: 22,
  },
}`,
}

export const SCENARIOS = {
  confirmation: SC_CONFIRMATION,
  advisor: SC_ADVISOR,
  wearable: SC_WEARABLE,
} as const

export function matchScenario(text: string, msgIndex: number) {
  const t = text.toLowerCase()
  if (t.includes('virement') || t.includes('confirm') || t.includes('rassurant') || t.includes('light') || t.includes('erreur') || t.includes('friction'))
    return SC_CONFIRMATION
  if (t.includes('advisor') || t.includes('agent') || t.includes('anxieux') || t.includes('investiss') || t.includes('fiscal') || t.includes('expert') || t.includes('escalade'))
    return SC_ADVISOR
  if (t.includes('watch') || t.includes('wearable') || t.includes('apple') || t.includes('adapt') || t.includes('series') || t.includes('haptique') || t.includes('accessib'))
    return SC_WEARABLE
  const keys = Object.values(SCENARIOS)
  return keys[msgIndex % keys.length]
}
