/**
 * mcpGenerator.ts — Generate a complete, ready-to-run MCP server
 * (Model Context Protocol) from an AgentSpec.
 *
 * The generated server is a self-contained TypeScript/Node.js file that:
 *   • Accepts tool calls via stdio (MCP transport)
 *   • Validates inputs against the spec constraints
 *   • Calls Claude with the spec's system prompt and config
 *   • Applies escalation logic based on capability and escalationRate
 *   • Handles errors and returns structured MCP responses
 *
 * Reference: https://modelcontextprotocol.io/docs/spec
 */

import type { AgentSpec } from "@/types";

// ---------------------------------------------------------------------------
// Output type
// ---------------------------------------------------------------------------

export interface McpGeneratorResult {
  /** The full TypeScript source code for the MCP server */
  serverCode: string;
  /** package.json content for the generated server */
  packageJson: string;
  /** README content */
  readme: string;
  /** Suggested file name */
  filename: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function jsString(s: string): string {
  return JSON.stringify(s);
}

function indent(code: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return code
    .split("\n")
    .map((l) => (l.trim() === "" ? "" : pad + l))
    .join("\n");
}

// ---------------------------------------------------------------------------
// Package.json generator
// ---------------------------------------------------------------------------

function generatePackageJson(spec: AgentSpec): string {
  const slug = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  return JSON.stringify(
    {
      name:    `@contextlayer/${slug}-mcp`,
      version: `1.0.${spec.version}`,
      description: spec.description || `MCP server for ${spec.name}`,
      main:    "server.js",
      scripts: {
        start:   "node server.js",
        build:   "tsc server.ts --outDir . --target ES2022 --module commonjs",
        dev:     "ts-node server.ts",
      },
      dependencies: {
        "@anthropic-ai/sdk": "^0.39.0",
        "@modelcontextprotocol/sdk": "^1.0.0",
      },
      devDependencies: {
        typescript:  "^5.7.0",
        "ts-node":   "^10.9.0",
        "@types/node": "^22.0.0",
      },
      engines: { node: ">=18.0.0" },
      license: "MIT",
    },
    null,
    2,
  );
}

// ---------------------------------------------------------------------------
// README generator
// ---------------------------------------------------------------------------

function generateReadme(spec: AgentSpec): string {
  const slug = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  return `# ${spec.name} — MCP Server

> Auto-generated by ContextLayer v${spec.version}

## Description

${spec.description || "No description provided."}

## Quick start

\`\`\`bash
npm install
export ANTHROPIC_API_KEY=your_key_here
node server.js
\`\`\`

## Configuration

| Field | Value |
|-------|-------|
| Model | \`${spec.model}\` |
| Max tokens | \`${spec.maxTokens}\` |
| Temperature | \`${spec.temperature}\` |
| Capabilities | ${spec.capabilities.join(", ") || "none"} |

## Tools

### \`run\`

Invoke the agent with a user prompt.

**Input schema**

\`\`\`json
{
  "prompt": "<string>",
  "context": "<string (optional)>"
}
\`\`\`

### \`validate\`

Validate a prompt against the agent spec without calling the model.

## MCP client config

Add to your \`mcp_settings.json\`:

\`\`\`json
{
  "mcpServers": {
    "${slug}": {
      "command": "node",
      "args": ["/path/to/${slug}-mcp/server.js"],
      "env": {
        "ANTHROPIC_API_KEY": "\${ANTHROPIC_API_KEY}"
      }
    }
  }
}
\`\`\`

---
*Generated from ContextLayer spec \`${spec.id}\` at ${new Date().toISOString()}*
`;
}

// ---------------------------------------------------------------------------
// Main server code generator
// ---------------------------------------------------------------------------

export function generateMcpServer(spec: AgentSpec): McpGeneratorResult {
  const slug        = spec.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 40);
  const escapedName = jsString(spec.name);
  const escapedDesc = jsString(spec.description || "");
  const escapedPrompt = jsString(spec.systemPrompt);
  const capList = JSON.stringify(spec.capabilities);

  // Build capability-based tool list
  const capabilityTools = spec.capabilities.includes("code")
    ? `\n    server.tool(\n      "run_code_review",\n      { code: z.string().describe("Code to review") },\n      async ({ code }) => runAgent(\`Review this code:\\n\\n\${code}\`)\n    );`
    : "";

  const serverCode = `/**
 * ${spec.name} — MCP Server
 * Auto-generated by ContextLayer
 *
 * Spec: ${spec.id}  |  Version: ${spec.version}
 * Model: ${spec.model}
 * Generated: ${new Date().toISOString()}
 *
 * DO NOT EDIT — regenerate from ContextLayer to pick up spec changes.
 */

import Anthropic        from "@anthropic-ai/sdk";
import { McpServer }    from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z }            from "zod";

// ---------------------------------------------------------------------------
// Spec constants (frozen from ContextLayer)
// ---------------------------------------------------------------------------

const SPEC = {
  id:          ${jsString(spec.id)},
  agentId:     ${jsString(spec.agentId)},
  name:        ${escapedName},
  description: ${escapedDesc},
  version:     ${spec.version},
  model:       ${jsString(spec.model)},
  systemPrompt: ${escapedPrompt},
  maxTokens:   ${spec.maxTokens},
  temperature: ${spec.temperature},
  capabilities: ${capList} as const,
} as const;

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

const PROHIBITED_PATTERNS: RegExp[] = (() => {
  const prohibitions: string[] = [];
  const systemLower = SPEC.systemPrompt.toLowerCase();
  const doNotPhrases = [
    ...systemLower.matchAll(/(?:do not|never|avoid|must not)\\s+([^.!?,;\\n]{3,40})/g),
  ].map((m) => m[1].trim());
  for (const phrase of doNotPhrases) {
    try { prohibitions.push(phrase); } catch { /* ignore */ }
  }
  const escapeRe = /[\\^$.*+?()\\[\\]{}|]/g;
  return prohibitions.map((p) => new RegExp(p.replace(escapeRe, "\\\\$&"), "i"));
})();

function validatePrompt(prompt: string): string[] {
  const issues: string[] = [];
  if (!prompt.trim()) issues.push("Prompt must not be empty");
  if (prompt.length > 50_000) issues.push("Prompt exceeds 50 000 characters");
  for (const pattern of PROHIBITED_PATTERNS) {
    if (pattern.test(prompt)) {
      issues.push(\`Prompt matches prohibited pattern: \${pattern.source}\`);
    }
  }
  return issues;
}

// ---------------------------------------------------------------------------
// Claude client
// ---------------------------------------------------------------------------

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

interface RunResult {
  response: string;
  inputTokens: number;
  outputTokens: number;
  latencyMs: number;
}

async function runAgent(
  userPrompt: string,
  extraContext?: string,
): Promise<RunResult> {
  const start = Date.now();

  const userContent = extraContext
    ? \`Context:\\n\${extraContext}\\n\\n---\\n\${userPrompt}\`
    : userPrompt;

  const message = await anthropic.messages.create({
    model:      SPEC.model,
    max_tokens: SPEC.maxTokens,
    temperature: SPEC.temperature,
    system:     SPEC.systemPrompt,
    messages:   [{ role: "user", content: userContent }],
  });

  const response =
    message.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("") || "(empty response)";

  return {
    response,
    inputTokens:  message.usage.input_tokens,
    outputTokens: message.usage.output_tokens,
    latencyMs:    Date.now() - start,
  };
}

// ---------------------------------------------------------------------------
// Escalation logic
// ---------------------------------------------------------------------------

function shouldEscalate(response: string): boolean {
  const lower = response.toLowerCase();
  const escalationSignals = [
    "i cannot", "i can't", "i'm unable", "outside my scope",
    "escalate", "human review", "supervisor",
  ];
  return escalationSignals.some((s) => lower.includes(s));
}

// ---------------------------------------------------------------------------
// MCP server
// ---------------------------------------------------------------------------

const server = new McpServer({
  name:    SPEC.name,
  version: String(SPEC.version),
});

// ── Tool: run ──────────────────────────────────────────────────────────────

server.tool(
  "run",
  {
    prompt:  z.string().describe("User prompt to send to the agent"),
    context: z.string().optional().describe("Optional extra context injected before the prompt"),
  },
  async ({ prompt, context }) => {
    // 1. Validate
    const issues = validatePrompt(prompt);
    if (issues.length > 0) {
      return {
        content: [{ type: "text", text: \`Validation failed:\\n\${issues.map((i) => \`• \${i}\`).join("\\n")}\` }],
        isError: true,
      };
    }

    // 2. Run
    let result: RunResult;
    try {
      result = await runAgent(prompt, context);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      return {
        content: [{ type: "text", text: \`Agent error: \${msg}\` }],
        isError: true,
      };
    }

    // 3. Escalation check
    const escalated = shouldEscalate(result.response);

    return {
      content: [
        {
          type: "text",
          text: result.response,
        },
      ],
      // Return metadata as second text block for consumers that read it
      ...(escalated || true
        ? {
            _meta: {
              specId:       SPEC.id,
              specVersion:  SPEC.version,
              model:        SPEC.model,
              inputTokens:  result.inputTokens,
              outputTokens: result.outputTokens,
              latencyMs:    result.latencyMs,
              escalated,
            },
          }
        : {}),
    };
  },
);

// ── Tool: validate ─────────────────────────────────────────────────────────

server.tool(
  "validate",
  { prompt: z.string().describe("Prompt to validate without calling the model") },
  async ({ prompt }) => {
    const issues = validatePrompt(prompt);
    const ok     = issues.length === 0;
    return {
      content: [
        {
          type: "text",
          text: ok
            ? "✓ Prompt is valid"
            : \`✗ \${issues.length} issue\${issues.length > 1 ? "s" : ""}:\\n\${issues.map((i) => \`  • \${i}\`).join("\\n")}\`,
        },
      ],
    };
  },
);

// ── Tool: spec_info ────────────────────────────────────────────────────────

server.tool(
  "spec_info",
  {},
  async () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name:         SPEC.name,
            description:  SPEC.description,
            version:      SPEC.version,
            model:        SPEC.model,
            maxTokens:    SPEC.maxTokens,
            temperature:  SPEC.temperature,
            capabilities: SPEC.capabilities,
          },
          null,
          2,
        ),
      },
    ],
  }),
);
${capabilityTools}

// ---------------------------------------------------------------------------
// Start
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("Error: ANTHROPIC_API_KEY environment variable is required");
    process.exit(1);
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(\`${spec.name} MCP server running (spec v\${SPEC.version})\`);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
`;

  return {
    serverCode,
    packageJson: generatePackageJson(spec),
    readme:      generateReadme(spec),
    filename:    `${slug}-mcp-server.ts`,
  };
}
